# Generated by Django 4.1 on 2023-02-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_document_token_tokenvalue_document_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('doc_id', models.IntegerField()),
                ('data', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tokenvalue',
            name='document',
        ),
        migrations.RemoveField(
            model_name='tokenvalue',
            name='token',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='TokenValue',
        ),
    ]
