# Generated by Django 4.1 on 2023-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_tokendata_remove_tokenvalue_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendata',
            name='data',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tokendata',
            name='doc_id',
            field=models.CharField(max_length=255),
        ),
    ]
